name             'uaitinode'
maintainer       'UaiTI'
maintainer_email 'contato@uaiti.com.br'
license          'all_rights'
description      'Installs/Configures uaitinode'
long_description 'Installs/Configures uaitinode'
version          '0.1.0'

depends 'nodejs', '~> 2.4.0'
depends 'mongodb', '~> 0.16.2'
depends 'application_nodejs'
